name: yolla
description: "Yolla project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  go_router: ^16.0.0
  pinput: ^5.0.1
  google_fonts: ^6.2.1
  jwt_decoder: ^2.0.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  rename: ^3.1.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  logger: ^2.6.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.1
  flutter_phoenix: ^1.1.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.1
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  mobile_scanner: ^7.0.1
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  freezed: ^3.1.0


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/vectors/
    - lib/src/data/



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
